
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRBmCPcWE3oaqICBgdSy_j6Ud9XioBtM',
    appId: '1:1096111989530:web:c864d3bb999499614182a3',
    messagingSenderId: '1096111989530',
    projectId: 'new-fellow-project',
    authDomain: 'new-fellow-project.firebaseapp.com',
    storageBucket: 'new-fellow-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC71VUj8eJVwb3NmfDazDLfI48MMmFnwf8',
    appId: '1:1096111989530:android:af7eec2014f387994182a3',
    messagingSenderId: '1096111989530',
    projectId: 'new-fellow-project',
    storageBucket: 'new-fellow-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAkSC1d8_mt2nkmGG_QOg0l3Wzk91nRbU',
    appId: '1:1096111989530:ios:4d616ac10046632b4182a3',
    messagingSenderId: '1096111989530',
    projectId: 'new-fellow-project',
    storageBucket: 'new-fellow-project.appspot.com',
    iosBundleId: 'com.example.frontendtpeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAkSC1d8_mt2nkmGG_QOg0l3Wzk91nRbU',
    appId: '1:1096111989530:ios:8db049ec46c656694182a3',
    messagingSenderId: '1096111989530',
    projectId: 'new-fellow-project',
    storageBucket: 'new-fellow-project.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
